version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: loan-mysql-db
    environment:
      MYSQL_DATABASE: loan_db
      MYSQL_ROOT_PASSWORD: MasterKey..
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pMasterKey.."]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loan-network

  backend:
    build: ./backend
    container_name: loan-backend-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/loan_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: MasterKey..
    depends_on:
      db:
        condition: service_healthy
    networks:
      - loan-network

  frontend:
    build: ./frontend
    container_name: loan-frontend-web
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - loan-network

networks:
  loan-network:
    driver: bridge
